##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.18.0-B7] date: [Mon Jan 09 16:50:49 MSK 2023]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------
#Set the toolchain dir here if you want
GCC_PATH = /c/tools/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi/bin

######################################
# target
######################################
TARGET = cm4


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/adc.c \
Core/Src/gpio.c \
Core/Src/spi.c \
Core/Src/stm32h7xx_hal_msp.c \
Core/Src/stm32h7xx_it.c \
Core/Src/syscalls.c \
Core/Src/sysmem.c \
Core/Src/tim.c \
Core/Src/usart.c \
../Common/Src/system_stm32h7xx_dualcore_boot_cm4_cm7.c\
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_adc.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_tim.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_exti.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_gpio.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rcc.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_spi.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usart.c \
../Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_utils.c \
../../boards/h745_nucleo/src_CM4/mbs_main_CM4.c \
../../boards/h745_nucleo/src_CM4/board_h745_nucleo_CM4.c \
../../mbs_drivers_h7/errno.c \
../../mbs_drivers_h7/mbs_flash.c \
../../mbs_drivers_h7/mbs_gpio.c \
../../mbs_drivers_h7/mbs_sci.c \
../../mbs_drivers_h7/mbs_spi.c \
../../mbs_drivers_h7/mbs_adc.c \
../../mbs_drivers_h7/mbs_tim.c \
../../mbs_drivers_h7/mbs_can.c \
../../mbs_drivers_h7/m95x.c \
../../mbs_drivers_h7/mbs_delay.c \
../../mbs_drivers_h7/pfunc.c \
../../mbs_drivers_h7/reg_access.c \






# ../Drivers/adk_hal/adk_hal_hsem.c \


# ASM sources
ASM_SOURCES = \
Core/Startup/startup_stm32h745zitx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H745xx \
-DUSE_FULL_LL_DRIVER \
-DCORE_CM4 \
-D_MEXBIOS_BB_ \
-DLM_IQMATH \
-DFLASH_MBS_CFG\
-DFLUORITE \
-DMB3_STOPBIT=1 \
-DH745_NUCLEO \
-DMB1 \
-DMB1_STOPBIT=1 \
-DMB1_PARITY=0 \
-DMB1_SPEED=192 \
-DMB1_ADR=1 \
-DMB_MODE=MB_RTU_SLAVE \
-DMB_SPEED=1152 \







# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES = \
-ICore/Inc \
-I../Drivers/CMSIS/Device/ST/STM32H7xx/Include \
-I../Drivers/CMSIS/Include \
-I../Drivers/STM32H7xx_HAL_Driver/Inc \
-I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-I../../mbs_drivers_h7 \
-I../.. \
-I../../boards/h745_nucleo/inc \
-I../../MexBiosKernel \



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H745ZITX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

#add libraries
MB_LIBS=\
../../MexBiosKernel/libSTM32H7XX.a \
../../MexBiosKernel/libkernel_m4f.a \
../../MexBiosKernel/IQmathLib-cm4f.a \
../../MexBiosKernel/libmodbus_rtu_m4f.a \



#../../MexBiosKernel/libIQmathLib-cm4f.a \



$(BUILD_DIR)/%.o: %.c makefile.mak | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s makefile.mak | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) makefile.mak
	$(CC) $(OBJECTS) $(MB_LIBS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@			

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
